-- Init file contains dependencies
require('plugins')
require('keybinds')
require('setting')
require('plugin_configs.onedark-config')
require('plugin_configs.nvim-tree-config')
require('plugin_configs.lualine-config')
require('plugin_configs.treesitter-config')
require('plugin_configs.telescope-config')
require('plugin_configs.bufferline-config')
require('plugin_configs.mason-config')
require('plugin_configs.gopls-config')
require('plugin_configs.dap-config')
require('plugin_configs.code-completion-config')
require('plugin_configs.auto-bracket-pair')
require('plugin_configs.auto-indent-config')

