-- Calling different configs from this init file
require('rupam.settings')
require('rupam.autocmd')
require('rupam.plugins')
require('rupam.keybinds')
require('rupam.plugin_config.nvim-tree')
require('rupam.plugin_config.lualine')
require('rupam.plugin_config.telescope')
require('rupam.plugin_config.treesitter')
require('rupam.plugin_config.buffer-line')
